useDotenv: true
# serverless.yml
service: hitokoto-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  profile: hitokoto 

  logs:
    restApi:
      executionLogging: true
      level: INFO

  # 事前に作成済みの S3 バケットを直接指定する
  deploymentBucket:
    name: hitokoto-app-dev-serverlessdeploybucket-abcdef


  environment:
    #UNSPLASH_ACCESS_KEY: ${ssm:/hitokoto/UNSPLASH_ACCESS_KEY}
    UNSPLASH_ACCESS_KEY: ${env:UNSPLASH_ACCESS_KEY}
    PHRASE_TABLE: { Ref: PhraseTable }
functions:
  api:
    handler: app.main.lambda_handler
    events:
      - httpApi: '*'
    environment:
      PHRASE_TABLE: { Ref: PhraseTable }
resources:
  Resources:
    PhraseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hitokoto-phrases-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: phrase_id
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: phrase_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hitokoto-images-${self:provider.stage}

